networks:
  hardhat:
    network_name: hardhat
    contract_address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  monad:
    network_name: monad
    contract_address: '0xb7f0079b02af704B9A6616ED7Cc3b616F6F48C49'
  fabric:
    network_name: fabric
    contract_address: ''
