networks:
  hardhat:
    network_name: hardhat
    contract_address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  monad:
    network_name: monad
    contract_address: '0x23EC7332865ecD204539f5C3535175C22D2C6388'
  fabric:
    network_name: fabric
    contract_address: ''
    file_index_path: 'data/fabric'
