// file-based btree index package 2024-06-10
// created by myjang@etri.re.kr
// Update 2024-12-05

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/index_server.proto

package idxserver_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HLFDataIndex_CreateIndex_FullMethodName         = "/idxserver.HLFDataIndex/CreateIndex"
	HLFDataIndex_InsertIndex_FullMethodName         = "/idxserver.HLFDataIndex/InsertIndex"
	HLFDataIndex_InsertSIndex_FullMethodName        = "/idxserver.HLFDataIndex/InsertSIndex"
	HLFDataIndex_GetindexDataByField_FullMethodName = "/idxserver.HLFDataIndex/GetindexDataByField"
)

// HLFDataIndexClient is the client API for HLFDataIndex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HLFDataIndexClient interface {
	CreateIndex(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*IdxResponse, error)
	InsertIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertData, IdxResponse], error)
	InsertSIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertSData, IdxResponse], error)
	GetindexDataByField(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*RstTxList, error)
}

type hLFDataIndexClient struct {
	cc grpc.ClientConnInterface
}

func NewHLFDataIndexClient(cc grpc.ClientConnInterface) HLFDataIndexClient {
	return &hLFDataIndexClient{cc}
}

func (c *hLFDataIndexClient) CreateIndex(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*IdxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdxResponse)
	err := c.cc.Invoke(ctx, HLFDataIndex_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hLFDataIndexClient) InsertIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertData, IdxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HLFDataIndex_ServiceDesc.Streams[0], HLFDataIndex_InsertIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InsertData, IdxResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HLFDataIndex_InsertIndexClient = grpc.ClientStreamingClient[InsertData, IdxResponse]

func (c *hLFDataIndexClient) InsertSIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertSData, IdxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HLFDataIndex_ServiceDesc.Streams[1], HLFDataIndex_InsertSIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InsertSData, IdxResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HLFDataIndex_InsertSIndexClient = grpc.ClientStreamingClient[InsertSData, IdxResponse]

func (c *hLFDataIndexClient) GetindexDataByField(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*RstTxList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RstTxList)
	err := c.cc.Invoke(ctx, HLFDataIndex_GetindexDataByField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HLFDataIndexServer is the server API for HLFDataIndex service.
// All implementations must embed UnimplementedHLFDataIndexServer
// for forward compatibility.
type HLFDataIndexServer interface {
	CreateIndex(context.Context, *CreateRequest) (*IdxResponse, error)
	InsertIndex(grpc.ClientStreamingServer[InsertData, IdxResponse]) error
	InsertSIndex(grpc.ClientStreamingServer[InsertSData, IdxResponse]) error
	GetindexDataByField(context.Context, *SearchRequest) (*RstTxList, error)
	mustEmbedUnimplementedHLFDataIndexServer()
}

// UnimplementedHLFDataIndexServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHLFDataIndexServer struct{}

func (UnimplementedHLFDataIndexServer) CreateIndex(context.Context, *CreateRequest) (*IdxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedHLFDataIndexServer) InsertIndex(grpc.ClientStreamingServer[InsertData, IdxResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InsertIndex not implemented")
}
func (UnimplementedHLFDataIndexServer) InsertSIndex(grpc.ClientStreamingServer[InsertSData, IdxResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InsertSIndex not implemented")
}
func (UnimplementedHLFDataIndexServer) GetindexDataByField(context.Context, *SearchRequest) (*RstTxList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetindexDataByField not implemented")
}
func (UnimplementedHLFDataIndexServer) mustEmbedUnimplementedHLFDataIndexServer() {}
func (UnimplementedHLFDataIndexServer) testEmbeddedByValue()                      {}

// UnsafeHLFDataIndexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HLFDataIndexServer will
// result in compilation errors.
type UnsafeHLFDataIndexServer interface {
	mustEmbedUnimplementedHLFDataIndexServer()
}

func RegisterHLFDataIndexServer(s grpc.ServiceRegistrar, srv HLFDataIndexServer) {
	// If the following call pancis, it indicates UnimplementedHLFDataIndexServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HLFDataIndex_ServiceDesc, srv)
}

func _HLFDataIndex_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HLFDataIndexServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HLFDataIndex_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HLFDataIndexServer).CreateIndex(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HLFDataIndex_InsertIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HLFDataIndexServer).InsertIndex(&grpc.GenericServerStream[InsertData, IdxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HLFDataIndex_InsertIndexServer = grpc.ClientStreamingServer[InsertData, IdxResponse]

func _HLFDataIndex_InsertSIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HLFDataIndexServer).InsertSIndex(&grpc.GenericServerStream[InsertSData, IdxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HLFDataIndex_InsertSIndexServer = grpc.ClientStreamingServer[InsertSData, IdxResponse]

func _HLFDataIndex_GetindexDataByField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HLFDataIndexServer).GetindexDataByField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HLFDataIndex_GetindexDataByField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HLFDataIndexServer).GetindexDataByField(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HLFDataIndex_ServiceDesc is the grpc.ServiceDesc for HLFDataIndex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HLFDataIndex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idxserver.HLFDataIndex",
	HandlerType: (*HLFDataIndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIndex",
			Handler:    _HLFDataIndex_CreateIndex_Handler,
		},
		{
			MethodName: "GetindexDataByField",
			Handler:    _HLFDataIndex_GetindexDataByField_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InsertIndex",
			Handler:       _HLFDataIndex_InsertIndex_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "InsertSIndex",
			Handler:       _HLFDataIndex_InsertSIndex_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protos/index_server.proto",
}
