services:
  grpcwebproxy:
    image: fullstorydev/grpcweb-proxy
    container_name: bi-index-grpcwebproxy
    ports:
      - "8080:8080"  # gRPC-Web 프록시 포트
    command: >
      --backend_addr=host.docker.internal:19001,host.docker.internal:50052
      --run_tls_server=false
      --allow_all_origins
      --server_http_debug_port=8080
      --server_http_max_read_timeout=60s
      --server_http_max_write_timeout=60s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    
  # Envoy 기반 프록시 (대안)
  envoy-proxy:
    image: envoyproxy/envoy:v1.25-latest
    container_name: bi-index-envoy
    ports:
      - "8081:8081"  # 포트 매핑 방식 사용
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    restart: unless-stopped
    profiles: ["envoy"]  # docker-compose --profile envoy up으로 실행
