// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: accessapi/access_management.proto

package accessapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 접근 요청 데이터
type AccessRequestData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceOwner    string                 `protobuf:"bytes,1,opt,name=resourceOwner,proto3" json:"resourceOwner,omitempty"`       // 데이터 소유자
	Purpose          string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`                   // 사용 목적
	OrganizationName string                 `protobuf:"bytes,3,opt,name=organizationName,proto3" json:"organizationName,omitempty"` // 조직명
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessRequestData) Reset() {
	*x = AccessRequestData{}
	mi := &file_accessapi_access_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequestData) ProtoMessage() {}

func (x *AccessRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequestData.ProtoReflect.Descriptor instead.
func (*AccessRequestData) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRequestData) GetResourceOwner() string {
	if x != nil {
		return x.ResourceOwner
	}
	return ""
}

func (x *AccessRequestData) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *AccessRequestData) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

// 상태 변경 요청
type StatusUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // 요청 ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`        // 상태 (APPROVED, REJECTED)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdateRequest) Reset() {
	*x = StatusUpdateRequest{}
	mi := &file_accessapi_access_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdateRequest) ProtoMessage() {}

func (x *StatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*StatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{1}
}

func (x *StatusUpdateRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *StatusUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 요청 조회
type RequestQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // 요청 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQuery) Reset() {
	*x = RequestQuery{}
	mi := &file_accessapi_access_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQuery) ProtoMessage() {}

func (x *RequestQuery) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQuery.ProtoReflect.Descriptor instead.
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{2}
}

func (x *RequestQuery) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// 소유자별 조회
type OwnerQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceOwner string                 `protobuf:"bytes,1,opt,name=resourceOwner,proto3" json:"resourceOwner,omitempty"` // 데이터 소유자
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerQuery) Reset() {
	*x = OwnerQuery{}
	mi := &file_accessapi_access_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerQuery) ProtoMessage() {}

func (x *OwnerQuery) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerQuery.ProtoReflect.Descriptor instead.
func (*OwnerQuery) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{3}
}

func (x *OwnerQuery) GetResourceOwner() string {
	if x != nil {
		return x.ResourceOwner
	}
	return ""
}

// 기본 응답
type AccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`     // 성공 여부
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // 응답 메시지
	RequestId     uint64                 `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"` // 요청 ID (생성시에만)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_accessapi_access_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{4}
}

func (x *AccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AccessResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// 요청 상세 응답
type AccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Request       *AccessRequestData     `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 0:PENDING, 1:APPROVED, 2:REJECTED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequestResponse) Reset() {
	*x = AccessRequestResponse{}
	mi := &file_accessapi_access_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequestResponse) ProtoMessage() {}

func (x *AccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequestResponse.ProtoReflect.Descriptor instead.
func (*AccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{5}
}

func (x *AccessRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccessRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AccessRequestResponse) GetRequest() *AccessRequestData {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AccessRequestResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 요청 목록 응답
type RequestListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestIds    []uint64               `protobuf:"varint,3,rep,packed,name=requestIds,proto3" json:"requestIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestListResponse) Reset() {
	*x = RequestListResponse{}
	mi := &file_accessapi_access_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestListResponse) ProtoMessage() {}

func (x *RequestListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestListResponse.ProtoReflect.Descriptor instead.
func (*RequestListResponse) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{6}
}

func (x *RequestListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestListResponse) GetRequestIds() []uint64 {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

// Purpose 검색 요청
type SearchByPurposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByPurposeRequest) Reset() {
	*x = SearchByPurposeRequest{}
	mi := &file_accessapi_access_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByPurposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByPurposeRequest) ProtoMessage() {}

func (x *SearchByPurposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByPurposeRequest.ProtoReflect.Descriptor instead.
func (*SearchByPurposeRequest) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{7}
}

func (x *SearchByPurposeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

// Purpose 검색 응답
type SearchByPurposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Requests      []*AccessRequestData   `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByPurposeResponse) Reset() {
	*x = SearchByPurposeResponse{}
	mi := &file_accessapi_access_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByPurposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByPurposeResponse) ProtoMessage() {}

func (x *SearchByPurposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accessapi_access_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByPurposeResponse.ProtoReflect.Descriptor instead.
func (*SearchByPurposeResponse) Descriptor() ([]byte, []int) {
	return file_accessapi_access_management_proto_rawDescGZIP(), []int{8}
}

func (x *SearchByPurposeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchByPurposeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchByPurposeResponse) GetRequests() []*AccessRequestData {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_accessapi_access_management_proto protoreflect.FileDescriptor

const file_accessapi_access_management_proto_rawDesc = "" +
	"\n" +
	"!accessapi/access_management.proto\x12\taccessapi\"\x7f\n" +
	"\x11AccessRequestData\x12$\n" +
	"\rresourceOwner\x18\x01 \x01(\tR\rresourceOwner\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12*\n" +
	"\x10organizationName\x18\x03 \x01(\tR\x10organizationName\"K\n" +
	"\x13StatusUpdateRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\fRequestQuery\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\x04R\trequestId\"2\n" +
	"\n" +
	"OwnerQuery\x12$\n" +
	"\rresourceOwner\x18\x01 \x01(\tR\rresourceOwner\"b\n" +
	"\x0eAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\x04R\trequestId\"\x9b\x01\n" +
	"\x15AccessRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\arequest\x18\x03 \x01(\v2\x1c.accessapi.AccessRequestDataR\arequest\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"i\n" +
	"\x13RequestListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"requestIds\x18\x03 \x03(\x04R\n" +
	"requestIds\"2\n" +
	"\x16SearchByPurposeRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\"\x87\x01\n" +
	"\x17SearchByPurposeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\brequests\x18\x03 \x03(\v2\x1c.accessapi.AccessRequestDataR\brequests2\xc9\x03\n" +
	"\x17AccessManagementService\x12L\n" +
	"\x11SaveAccessRequest\x12\x1c.accessapi.AccessRequestData\x1a\x19.accessapi.AccessResponse\x12V\n" +
	"\x19UpdateAccessRequestStatus\x12\x1e.accessapi.StatusUpdateRequest\x1a\x19.accessapi.AccessResponse\x12M\n" +
	"\x10GetAccessRequest\x12\x17.accessapi.RequestQuery\x1a .accessapi.AccessRequestResponse\x12Q\n" +
	"\x18GetAccessRequestsByOwner\x12\x15.accessapi.OwnerQuery\x1a\x1e.accessapi.RequestListResponse\x12f\n" +
	"\x1dSearchAccessRequestsByPurpose\x12!.accessapi.SearchByPurposeRequest\x1a\".accessapi.SearchByPurposeResponseB\rZ\v./accessapib\x06proto3"

var (
	file_accessapi_access_management_proto_rawDescOnce sync.Once
	file_accessapi_access_management_proto_rawDescData []byte
)

func file_accessapi_access_management_proto_rawDescGZIP() []byte {
	file_accessapi_access_management_proto_rawDescOnce.Do(func() {
		file_accessapi_access_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accessapi_access_management_proto_rawDesc), len(file_accessapi_access_management_proto_rawDesc)))
	})
	return file_accessapi_access_management_proto_rawDescData
}

var file_accessapi_access_management_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_accessapi_access_management_proto_goTypes = []any{
	(*AccessRequestData)(nil),       // 0: accessapi.AccessRequestData
	(*StatusUpdateRequest)(nil),     // 1: accessapi.StatusUpdateRequest
	(*RequestQuery)(nil),            // 2: accessapi.RequestQuery
	(*OwnerQuery)(nil),              // 3: accessapi.OwnerQuery
	(*AccessResponse)(nil),          // 4: accessapi.AccessResponse
	(*AccessRequestResponse)(nil),   // 5: accessapi.AccessRequestResponse
	(*RequestListResponse)(nil),     // 6: accessapi.RequestListResponse
	(*SearchByPurposeRequest)(nil),  // 7: accessapi.SearchByPurposeRequest
	(*SearchByPurposeResponse)(nil), // 8: accessapi.SearchByPurposeResponse
}
var file_accessapi_access_management_proto_depIdxs = []int32{
	0, // 0: accessapi.AccessRequestResponse.request:type_name -> accessapi.AccessRequestData
	0, // 1: accessapi.SearchByPurposeResponse.requests:type_name -> accessapi.AccessRequestData
	0, // 2: accessapi.AccessManagementService.SaveAccessRequest:input_type -> accessapi.AccessRequestData
	1, // 3: accessapi.AccessManagementService.UpdateAccessRequestStatus:input_type -> accessapi.StatusUpdateRequest
	2, // 4: accessapi.AccessManagementService.GetAccessRequest:input_type -> accessapi.RequestQuery
	3, // 5: accessapi.AccessManagementService.GetAccessRequestsByOwner:input_type -> accessapi.OwnerQuery
	7, // 6: accessapi.AccessManagementService.SearchAccessRequestsByPurpose:input_type -> accessapi.SearchByPurposeRequest
	4, // 7: accessapi.AccessManagementService.SaveAccessRequest:output_type -> accessapi.AccessResponse
	4, // 8: accessapi.AccessManagementService.UpdateAccessRequestStatus:output_type -> accessapi.AccessResponse
	5, // 9: accessapi.AccessManagementService.GetAccessRequest:output_type -> accessapi.AccessRequestResponse
	6, // 10: accessapi.AccessManagementService.GetAccessRequestsByOwner:output_type -> accessapi.RequestListResponse
	8, // 11: accessapi.AccessManagementService.SearchAccessRequestsByPurpose:output_type -> accessapi.SearchByPurposeResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_accessapi_access_management_proto_init() }
func file_accessapi_access_management_proto_init() {
	if File_accessapi_access_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accessapi_access_management_proto_rawDesc), len(file_accessapi_access_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accessapi_access_management_proto_goTypes,
		DependencyIndexes: file_accessapi_access_management_proto_depIdxs,
		MessageInfos:      file_accessapi_access_management_proto_msgTypes,
	}.Build()
	File_accessapi_access_management_proto = out.File
	file_accessapi_access_management_proto_goTypes = nil
	file_accessapi_access_management_proto_depIdxs = nil
}
